PROJECT/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("admin_panel.urls")),
    path("", include("bot.urls")),
]

if settings.DEBUG:
    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(prefix=settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin_panel/urls.py
from django.urls import path

from .views import UsersListView, QuestionsListView, QuestionEditView

urlpatterns = [
    path("", UsersListView.as_view(), name="users_list"),
    path("question_list/", QuestionsListView.as_view(), name="questions_list"),
    path("question_edit/<int:pk>", QuestionEditView.as_view(), name="question_edit")
]

bot/urls.py
from django.urls import path

from .views import UpdateBot, WebhookBot
from .settings import BOT_TOKEN

urlpatterns = [
    path("webhook/", WebhookBot.as_view(), name="webhook"),
    path(f"webhook{BOT_TOKEN}/", UpdateBot.as_view(), name="update")
]

admin_panel/models.py
from django.db import models


class TelegramUser(models.Model):
    STATUS_LOGGED = "Авторизовался"
    STATUS_ACTIVE = "Проходит викторину"
    STATUS_END = "Закончил викторину"

    STATUS_CHOICES = [
        (STATUS_LOGGED, "Авторизовался"),
        (STATUS_ACTIVE, "Проходит викторину"),
        (STATUS_END, "Закончил викторину")
    ]

    first_name = models.CharField(max_length=255, verbose_name="Имя")
    last_name = models.CharField(max_length=255, verbose_name="Фамилия")
    username = models.CharField(max_length=255, verbose_name="Имя пользователя")
    telegram_id = models.IntegerField(verbose_name="Telegram ID")
    true_answer = models.PositiveIntegerField(verbose_name="Правильных ответов", default=0)
    false_answer = models.PositiveIntegerField(verbose_name="Неправильных ответов", default=0)
    current_question = models.PositiveIntegerField(verbose_name="Текущий вопрос", default=0)
    status = models.CharField(max_length=255, verbose_name="Статус", choices=STATUS_CHOICES, default=STATUS_LOGGED)
    start_game = models.DateTimeField(auto_now_add=True, verbose_name="Начало викторины", null=True)
    duration_game = models.CharField(max_length=255, verbose_name="Продолжительтельность игры", default=0)

    def __str__(self):
        return f"{self.first_name} - {self.telegram_id}"

    class Meta:
        verbose_name = "Пользователь Telegram"
        verbose_name_plural = "Пользователи Telegram"


class Questions(models.Model):
    title = models.CharField(max_length=255, verbose_name="Вопрос")
    answer = models.CharField(max_length=255, verbose_name="Ответ")
    image = models.ImageField(upload_to="question_photos/", verbose_name="Картинка", null=True, blank=True)
    answer_option_one = models.CharField(max_length=255, verbose_name="Вариант ответа 1")
    answer_option_two = models.CharField(max_length=255, verbose_name="Вариант ответа 2")
    answer_option_third = models.CharField(max_length=255, verbose_name="Вариант ответа 3")
    answer_option_four = models.CharField(max_length=255, verbose_name="Вариант ответа 4")

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "Вопрос"
        verbose_name_plural = "Вопросы"

admin_panel/forms.py
from django import forms
from .models import Questions


class QuestionsForm(forms.ModelForm):
    class Meta:
        model = Questions
        fields = (
            "title", "answer", "image", "answer_option_one", "answer_option_two", "answer_option_third", "answer_option_four"
        )
        widgets = {
            "title": forms.TextInput(attrs={
                "class": "form-control"
            }),
            "answer": forms.TextInput(attrs={
                "class": "form-control"
            }),
            "answer_option_one": forms.TextInput(attrs={
                "class": "form-control"
            }),
            "answer_option_two": forms.TextInput(attrs={
                "class": "form-control"
            }),
            "answer_option_third": forms.TextInput(attrs={
                "class": "form-control"
            }),
            "answer_option_four": forms.TextInput(attrs={
                "class": "form-control"
            }),

        }

admin_panel/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView
from django.views import View
from django.contrib import messages
from django.db.models import Q

from .models import TelegramUser, Questions
from .forms import QuestionsForm


class UsersListView(View):
    def get(self, request):
        active_users = TelegramUser.objects.filter(Q(status="Проходит викторину") | Q(status="Авторизовался")).order_by("current_question")
        finish_users = TelegramUser.objects.filter(status="Закончил викторину").order_by("true_answer")
        return render(request, "admin_panel/users_list.html", {
            "title": "Главная",
            "active_users": active_users,
            "finish_users": finish_users
        })


class QuestionsListView(View):
    def get(self, request):
        form = QuestionsForm()
        questions_list = Questions.objects.all()
        return render(request, "admin_panel/questions_list.html", {
            "form": form,
            "questions_list": questions_list,
            "title": "Список вопросов"
        })

    def post(self, request):
        form = QuestionsForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            question = form.save()
            messages.success(request, "Вопрос успешно добавлен.")
            return redirect("questions_list")
        else:
            messages.error(request, "Ошибка добавления.")
            return redirect("questions_list")


class QuestionEditView(UpdateView):
    model = Questions
    form_class = QuestionsForm
    template_name = "admin_panel/question_edit.html"
    extra_context = {
        "title": "Изменить вопрос",
    }

    def get_queryset(self):
        return Questions.objects.filter(pk=self.kwargs.get("pk"))

    def get_success_url(self):
        messages.success(self.request, "Вопрос успешно обновлен.")
        return reverse_lazy("questions_list")

bot/views.py
from telebot import types
from rest_framework.response import Response
from rest_framework.views import APIView
from .settings import WEBHOOK_URL

from django.http import HttpResponse
from django.views import View

from .bot import bot


class UpdateBot(APIView):
    @staticmethod
    def post(request):
        json_str = request.body.decode("UTF-8")
        update = types.Update.de_json(json_str)
        bot.process_new_updates([update])

        return Response({"code": 200})


class WebhookBot(View):
    def get(self, request):
        print("Бот запущен !")
        bot.delete_webhook(drop_pending_updates=True)
        response = bot.set_webhook(url=WEBHOOK_URL)
        if response:
            return HttpResponse(f"<h1>Бот запущен !</h1><p>{WEBHOOK_URL}</p>")
        return HttpResponse("<h1>Ошибка запуска</h1>")

admin_panel/templates/admin_panel/question_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<div class="container-fluid">
    <div class="row justify-content-between">
        <div class="col-md-3">
            {% include 'components/_sidebar.html' %}
        </div>
        <div class="col-md-9">
            <div class="row justify-content-center">
                <h2 class="text-center mt-3 mb-5">Изменить вопрос</h2>
                {% if messages %}
                {% for message in messages %}
                {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
                {% else %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
                {% endif %}
                {% endfor %}
                {% endif %}

                <form action="" method="post" enctype="multipart/form-data" style="width: 600px">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Изменить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

admin_panel/templates/admin_panel/questions_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-between">
        <div class="col-md-3">
            {% include 'components/_sidebar.html' %}
        </div>
        <div class="col-md-9">
            <div class="row justify-content-center">
                <h2 class="text-center mt-3 mb-5">Добавить вопрос</h2>
                {% if messages %}
                {% for message in messages %}
                {% if message.tags == 'error' %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
                {% else %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
                {% endif %}
                {% endfor %}
                {% endif %}

                <form action="" method="post" enctype="multipart/form-data" style="width: 600px">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Добавить</button>
                </form>
            </div>

            <div class="row">
                <h2 class="mt-5 mb-5 text-center">Список вопросов</h2>
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr class="text-center">
                                <th>#</th>
                                <th>Вопрос</th>
                                <th>Ответ</th>
                                <th>Вариант ответа 1</th>
                                <th>Вариант ответа 2</th>
                                <th>Вариант ответа 3</th>
                                <th>Вариант ответа 4</th>
                                <th>Картинка</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for question in questions_list %}
                            <tr class="text-center">
                                <td style="height: 80px;">{{ question.pk }}</td>
                                <td style="height: 80px;">{{ question.title }}</td>
                                <td style="height: 80px;">{{ question.answer }}</td>
                                <td style="height: 80px;">{{ question.answer_option_one }}</td>
                                <td style="height: 80px;">{{ question.answer_option_two }}</td>
                                <td style="height: 80px;">{{ question.answer_option_third }}</td>
                                <td style="height: 80px;">{{ question.answer_option_four }}</td>
                                {% if question.image %}
                                <td>
                                    <a href="{{ question.image.url }}">
                                        <img src="{{ question.image.url }}" alt="" width="50px" height="50px">
                                    </a>
                                </td>
                                {% else %}
                                <td>Пусто</td>
                                {% endif %}
                                <td><a href="{% url 'question_edit' pk=question.pk %}"
                                        class="btn btn-warning">Изменить</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

            <script>
                // Помощь заполнения первого варианта ответа
                const answerField = document.querySelector("#id_answer")
                const answerOptionOneField = document.querySelector("#id_answer_option_one")

                answerField.addEventListener("input", () => {
                    answerOptionOneField.value = answerField.value
                })
            </script>
        </div>
    </div>
</div>
{% endblock content %}

admin_panel/templates/admin_panel/users_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <div class="row justify-content-between">
        <div class="col-md-3">
            {% include 'components/_sidebar.html' %}
        </div>
        <div class="col-md-9">
            <div id="app">
                <h2>Активные пользователи</h2>
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr class="text-center">
                                <th>#</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>username</th>
                                <th>Текущий вопрос</th>
                                <th>Статус</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in active_users %}
                            <tr class="text-center">
                                <td>{{ user.pk }}</td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.username }}</td>
                                <td>{{ user.current_question }}</td>
                                <td>{{ user.status }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <h2>Викторину закончили</h2>
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr class="text-center">
                                <th>#</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>username</th>
                                <th>Правильных ответов</th>
                                <th>Неправильных ответов</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in finish_users %}
                            <tr class="text-center">
                                <td>{{ user.pk }}</td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.last_name }}</td>
                                <td>{{ user.username }}</td>
                                <td>{{ user.true_answer }}</td>
                                <td>{{ user.false_answer }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <script>
                setInterval(() => { location.reload() }, 5000)
            </script>
        </div>
    </div>
</div>
{% endblock content %}

admin_panel/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
</head>
<body>

{% block content %} {% endblock content %}

</body>
</html>

admin_panel/templates/components/_sidebar.html
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
    <svg class="bi me-2" width="40" height="32">
      <use xlink:href="#bootstrap"></use>
    </svg>
    <span class="fs-4">QUIZ ADMIN PANEL</span>
  </a>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <a href="{% url 'users_list' %}" class="nav-link text-white" aria-current="page">
        <svg class="bi me-2" width="16" height="16">
          <use xlink:href="#home"></use>
        </svg>
        Главная
      </a>
    </li>
    <li>
      <a href="{% url 'questions_list' %}" class="nav-link text-white">
        <svg class="bi me-2" width="16" height="16">
          <use xlink:href="#speedometer2"></use>
        </svg>
        Список вопросов
      </a>
    </li>
  </ul>
</div>


<script>
  // Смена активной страницы
  const nav = document.querySelector(".nav")
  const navLink = nav.querySelectorAll(".nav-link")
  
  const mainPage = `${document.location.protocol}//${document.location.host}/`
  const questionsPage = `${document.location.protocol}//${document.location.host}/question_list/`

  const routes = {}
  routes[mainPage] = "Главная"
  routes[questionsPage] = "Список вопросов"

  for (let i = 0; i < navLink.length; i++) {
    if (navLink[i].textContent.trim() == routes[window.location.href]) {
      navLink[i].classList.add("active")
    }
  }


</script>